"""
Deduplication Service for Repository Automation

A centralized module for detecting duplicate events, self-comments, and
preventing infinite loops in webhook-triggered workflows.

This module provides deterministic functions that both webhook_handler.py
and repository_automation.py can use to check if an event should be processed.

Key Concepts:
- comment_id: The unique ID of a comment from GitHub/Forgejo API
- hash_id: A generated hash for deduplication (format: <!-- agix-id: {hash} -->)
- trigger_id: Identifies what triggered the response (e.g., "initial" or "reply_to_{id}")

Usage:
    from python.helpers.dedup_service import (
        is_self_generated_comment,
        should_respond_to_comment,
        extract_agix_hash,
        generate_dedup_hash,
        has_handled_comment
    )
"""

import re
import logging
from typing import Dict, Any, Optional, Tuple

logger = logging.getLogger("dedup-service")

# =============================================================================
# Constants
# =============================================================================

# Markers that indicate a comment was generated by the system
SELF_MARKERS = [
    "<!-- agix-id:",
    "agix-id:",
    "🤖 Comment Assistant:",
    "🎯 Expert Solution Analysis:",
    "AI-HANDLED:",
    "<!-- AI-ANALYSIS",
]

# Bot account patterns (case-insensitive)
BOT_PATTERNS = [
    "[bot]",
    "-bot",
    "_bot",
    "bot-",
    "automation",
]


# =============================================================================
# Core Detection Functions
# =============================================================================


def is_self_generated_comment(comment_body: str) -> bool:
    """
    Check if a comment body contains markers indicating it was generated by the system.
    
    This is the PRIMARY check for preventing infinite loops. If a comment has any
    of these markers, the system should NOT generate a new response.
    
    Args:
        comment_body: The raw text content of the comment
        
    Returns:
        True if the comment was generated by the system, False otherwise
        
    Examples:
        >>> is_self_generated_comment("Hello world")
        False
        >>> is_self_generated_comment("Analysis complete <!-- agix-id: abc123 -->")
        True
        >>> is_self_generated_comment("🤖 Comment Assistant: Here's my analysis...")
        True
    """
    if not comment_body:
        return False
    
    for marker in SELF_MARKERS:
        if marker in comment_body:
            logger.debug(f"[DEDUP] Self-generated comment detected (marker: {marker})")
            return True
    
    return False


def is_bot_account(username: str, user_type: str = "") -> bool:
    """
    Check if a user account appears to be a bot.
    
    Args:
        username: The login/username of the commenter
        user_type: The user type field from API (e.g., "User", "Bot")
        
    Returns:
        True if the account appears to be a bot
        
    Examples:
        >>> is_bot_account("dependabot[bot]", "Bot")
        True
        >>> is_bot_account("your-org", "User")
        False
        >>> is_bot_account("github-actions[bot]", "Bot")
        True
    """
    if not username:
        return False
    
    # Explicit bot type
    if user_type and user_type.lower() == "bot":
        return True
    
    username_lower = username.lower()
    for pattern in BOT_PATTERNS:
        if pattern in username_lower:
            return True
    
    return False


def extract_agix_hash(comment_body: str) -> Optional[str]:
    """
    Extract the agix-id hash from a comment body.
    
    Args:
        comment_body: The raw text content of the comment
        
    Returns:
        The hash string if found, None otherwise
        
    Examples:
        >>> extract_agix_hash("Hello <!-- agix-id: abc123def -->")
        'abc123def'
        >>> extract_agix_hash("No hash here")
        None
    """
    if not comment_body:
        return None
    
    # Match both formats: <!-- agix-id: xxx --> and agix-id: xxx
    patterns = [
        r'<!-- agix-id:\s*(\w+)\s*-->',
        r'agix-id:\s*(\w+)',
    ]
    
    for pattern in patterns:
        match = re.search(pattern, comment_body)
        if match:
            return match.group(1)
    
    return None


def generate_dedup_hash(issue_number: int, trigger_id: str = "initial") -> str:
    """
    Generate a deduplication hash for a response.
    
    The hash is deterministic based on issue number and trigger, ensuring
    that the same response attempt produces the same hash.
    
    Args:
        issue_number: The issue number being responded to
        trigger_id: What triggered this response (e.g., "initial", "reply_to_123")
        
    Returns:
        A 12-character hash string
        
    Examples:
        >>> generate_dedup_hash(42, "initial")
        '9f86d081884c'  # Example - actual hash is deterministic
        >>> generate_dedup_hash(42, "reply_to_100")
        'a3c35f4e5d8c'  # Different hash for different trigger
    """
    from python.helpers.hashing import content_hash_short
    content = f"{issue_number}:{trigger_id}"
    return content_hash_short(content, length=12)


def generate_hash_tag(hash_id: str) -> str:
    """
    Generate the HTML comment tag for embedding in responses.
    
    Args:
        hash_id: The deduplication hash
        
    Returns:
        HTML comment string
        
    Examples:
        >>> generate_hash_tag("abc123")
        '\\n\\n<!-- agix-id: abc123 -->'
    """
    return f"\n\n<!-- agix-id: {hash_id} -->"


# =============================================================================
# Comment Analysis Functions
# =============================================================================


def should_respond_to_comment(
    comment_body: str,
    comment_user: str = "",
    comment_user_type: str = "",
    issue_comments: list = None
) -> Tuple[bool, str]:
    """
    Determine if the system should generate a response to this comment.
    
    This is the main entry point for checking if we should respond.
    It runs all relevant checks and returns a decision with reason.
    
    Args:
        comment_body: The body of the triggering comment
        comment_user: Username of the commenter
        comment_user_type: User type (e.g., "User", "Bot")
        issue_comments: Optional list of all comments on the issue (for context)
        
    Returns:
        Tuple of (should_respond: bool, reason: str)
        
    Examples:
        >>> should_respond_to_comment("Please help", "your-org", "User")
        (True, "ok")
        >>> should_respond_to_comment("Analysis complete <!-- agix-id: xxx -->", "agix-bot")
        (False, "self_generated")
    """
    # Check 1: Self-generated comment
    if is_self_generated_comment(comment_body):
        return (False, "self_generated")
    
    # Check 2: Bot account
    if is_bot_account(comment_user, comment_user_type):
        return (False, f"bot_account:{comment_user}")
    
    # Check 3: If we have the full comment list, check if last N comments are all self-generated
    # This catches edge cases where multiple bot responses exist
    if issue_comments and len(issue_comments) > 0:
        consecutive_self = 0
        for c in reversed(issue_comments):
            body = c.get("body", "") if isinstance(c, dict) else ""
            if is_self_generated_comment(body):
                consecutive_self += 1
            else:
                break
        
        # If last 3+ comments are all self-generated, something is wrong - stop
        if consecutive_self >= 3:
            return (False, f"loop_detected:{consecutive_self}_consecutive_self")
    
    return (True, "ok")


def find_last_human_comment_id(comments: list) -> Optional[int]:
    """
    Find the ID of the last comment that was NOT made by the system.
    
    This is used to generate a proper trigger_id for deduplication hashes.
    
    Args:
        comments: List of comment dicts with 'id', 'body', 'user' fields
        
    Returns:
        The comment ID of the last human comment, or None if all are self-generated
    """
    if not comments:
        return None
    
    for c in reversed(comments):
        body = c.get("body", "")
        user = c.get("user", {})
        username = user.get("login", "") if isinstance(user, dict) else ""
        user_type = user.get("type", "") if isinstance(user, dict) else ""
        
        if not is_self_generated_comment(body) and not is_bot_account(username, user_type):
            return c.get("id")
    
    return None


def has_handled_comment(
    comments: list,
    target_hash: str = None,
    expected_trigger_id: str = None,
    issue_number: int = None
) -> bool:
    """
    Check if we've already responded to comments with the given hash or trigger.
    
    This queries the existing comments to see if a response with our hash exists.
    
    Args:
        comments: List of comment dicts with 'body' field
        target_hash: Specific hash to look for
        expected_trigger_id: If no target_hash, compute from trigger_id + issue_number
        issue_number: Issue number for hash computation
        
    Returns:
        True if a response with matching hash already exists
    """
    if not comments:
        return False
    
    # Compute hash if not provided directly
    if not target_hash and expected_trigger_id and issue_number:
        target_hash = generate_dedup_hash(issue_number, expected_trigger_id)
    
    if not target_hash:
        logger.warning("[DEDUP] has_handled_comment called without hash or trigger_id")
        return False
    
    # Check all comments for this hash
    for c in comments:
        body = c.get("body", "")
        found_hash = extract_agix_hash(body)
        if found_hash == target_hash:
            logger.info(f"[DEDUP] Found existing response with hash {target_hash}")
            return True
    
    return False


# =============================================================================
# High-Level Deduplication Check
# =============================================================================


def check_should_respond(
    issue_number: int,
    triggering_comment_id: int,
    triggering_comment_body: str,
    triggering_comment_user: str,
    triggering_comment_user_type: str,
    all_comments: list
) -> Dict[str, Any]:
    """
    Comprehensive check for whether to respond to a comment.
    
    This is the main function that repository_automation._answer_comment should call.
    It performs all checks and returns a detailed result.
    
    Args:
        issue_number: Issue number
        triggering_comment_id: ID of the comment that triggered this check
        triggering_comment_body: Body of the triggering comment
        triggering_comment_user: Username of the triggering comment author
        triggering_comment_user_type: User type of the triggering comment author
        all_comments: List of all comments on the issue
        
    Returns:
        Dict with keys:
            - respond: bool - True if should respond
            - reason: str - Explanation
            - hash_id: str - Hash to use if responding
            - trigger_id: str - Trigger ID used for hash generation
    """
    result = {
        "respond": False,
        "reason": "",
        "hash_id": "",
        "trigger_id": ""
    }
    
    # Step 1: Check if we should respond at all
    should_respond, reason = should_respond_to_comment(
        triggering_comment_body,
        triggering_comment_user,
        triggering_comment_user_type,
        all_comments
    )
    
    if not should_respond:
        result["reason"] = reason
        return result
    
    # Step 2: Generate trigger ID (what are we responding to?)
    trigger_id = f"reply_to_{triggering_comment_id}"
    result["trigger_id"] = trigger_id
    
    # Step 3: Generate hash for this response
    hash_id = generate_dedup_hash(issue_number, trigger_id)
    result["hash_id"] = hash_id
    
    # Step 4: Check if we've already responded with this hash
    if has_handled_comment(all_comments, target_hash=hash_id):
        result["reason"] = f"already_responded:{hash_id}"
        return result
    
    # All checks passed - should respond
    result["respond"] = True
    result["reason"] = "ok"
    return result


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    # Core detection
    'is_self_generated_comment',
    'is_bot_account',
    'extract_agix_hash',
    # Hash generation
    'generate_dedup_hash',
    'generate_hash_tag',
    # Analysis
    'should_respond_to_comment',
    'find_last_human_comment_id',
    'has_handled_comment',
    # High-level
    'check_should_respond',
    # Constants
    'SELF_MARKERS',
    'BOT_PATTERNS',
]