from __future__ import annotations
"""
Observer Mesh for Parallel Swarm Monitoring

Provides distributed observability across the agent swarm:
- Real-time metrics collection
- Event streaming and aggregation
- Health monitoring and alerting
- Performance tracking
- Distributed tracing support
"""

import asyncio
import logging
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set, Awaitable
import json

logger = logging.getLogger(__name__)


class MetricType(Enum):
    """Types of metrics that can be collected."""
    COUNTER = "counter"       # Monotonically increasing value
    GAUGE = "gauge"           # Point-in-time value
    HISTOGRAM = "histogram"   # Distribution of values
    SUMMARY = "summary"       # Statistical summary
    LATENCY = "latency"       # Time-based measurement


class EventType(Enum):
    """Types of events in the observer mesh."""
    TASK_STARTED = "task_started"
    TASK_COMPLETED = "task_completed"
    TASK_FAILED = "task_failed"
    AGENT_SPAWNED = "agent_spawned"
    AGENT_TERMINATED = "agent_terminated"
    WAVE_STARTED = "wave_started"
    WAVE_COMPLETED = "wave_completed"
    ERROR_OCCURRED = "error_occurred"
    RETRY_ATTEMPTED = "retry_attempted"
    CIRCUIT_OPENED = "circuit_opened"
    CIRCUIT_CLOSED = "circuit_closed"
    MEMORY_STORED = "memory_stored"
    MEMORY_RETRIEVED = "memory_retrieved"
    API_REQUEST_STARTED = "api_request_started"
    API_REQUEST_COMPLETED = "api_request_completed"
    TOOL_EXECUTION_STARTED = "tool_execution_started"
    TOOL_EXECUTION_COMPLETED = "tool_execution_completed"
    PROMPT_RENDERED = "prompt_rendered"
    CUSTOM = "custom"


class AlertSeverity(Enum):
    """Severity levels for alerts."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class Metric:
    """A single metric measurement."""
    name: str
    type: MetricType
    value: float
    timestamp: datetime
    labels: Dict[str, str] = field(default_factory=dict)
    unit: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "type": self.type.value,
            "value": self.value,
            "timestamp": self.timestamp.isoformat(),
            "labels": self.labels,
            "unit": self.unit,
        }
    
    def to_prometheus(self) -> str:
        """Format as Prometheus metric."""
        labels_str = ""
        if self.labels:
            label_pairs = [f'{k}="{v}"' for k, v in self.labels.items()]
            labels_str = "{" + ",".join(label_pairs) + "}"
        return f"{self.name}{labels_str} {self.value}"


@dataclass
class Event:
    """An event in the observer mesh."""
    id: str
    type: EventType
    timestamp: datetime
    source: str
    data: Dict[str, Any] = field(default_factory=dict)
    trace_id: Optional[str] = None
    span_id: Optional[str] = None
    parent_span_id: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "type": self.type.value,
            "timestamp": self.timestamp.isoformat(),
            "source": self.source,
            "data": self.data,
            "trace_id": self.trace_id,
            "span_id": self.span_id,
            "parent_span_id": self.parent_span_id,
        }


@dataclass
class Alert:
    """An alert generated by the observer mesh."""
    id: str
    severity: AlertSeverity
    title: str
    message: str
    timestamp: datetime
    source: str
    labels: Dict[str, str] = field(default_factory=dict)
    resolved: bool = False
    resolved_at: Optional[datetime] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "severity": self.severity.value,
            "title": self.title,
            "message": self.message,
            "timestamp": self.timestamp.isoformat(),
            "source": self.source,
            "labels": self.labels,
            "resolved": self.resolved,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
        }


@dataclass
class Span:
    """A tracing span for distributed tracing."""
    trace_id: str
    span_id: str
    parent_span_id: Optional[str]
    operation_name: str
    start_time: datetime
    end_time: Optional[datetime] = None
    status: str = "ok"
    tags: Dict[str, str] = field(default_factory=dict)
    logs: List[Dict[str, Any]] = field(default_factory=list)
    
    @property
    def duration_ms(self) -> Optional[float]:
        if self.end_time:
            return (self.end_time - self.start_time).total_seconds() * 1000
        return None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "span_id": self.span_id,
            "parent_span_id": self.parent_span_id,
            "operation_name": self.operation_name,
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat() if self.end_time else None,
            "duration_ms": self.duration_ms,
            "status": self.status,
            "tags": self.tags,
            "logs": self.logs,
        }


class MetricsCollector:
    """Collects and aggregates metrics."""
    
    def __init__(self, max_history: int = 10000):
        self.max_history = max_history
        self._metrics: Dict[str, List[Metric]] = {}
        self._counters: Dict[str, float] = {}
        self._gauges: Dict[str, float] = {}
        self._histograms: Dict[str, List[float]] = {}
        self._lock = asyncio.Lock()
    
    async def increment(
        self,
        name: str,
        value: float = 1.0,
        labels: Optional[Dict[str, str]] = None
    ) -> None:
        """Increment a counter metric."""
        async with self._lock:
            key = self._make_key(name, labels)
            self._counters[key] = self._counters.get(key, 0) + value
            
            metric = Metric(
                name=name,
                type=MetricType.COUNTER,
                value=self._counters[key],
                timestamp=datetime.now(timezone.utc),
                labels=labels or {},
            )
            self._store_metric(metric)
    
    async def gauge(
        self,
        name: str,
        value: float,
        labels: Optional[Dict[str, str]] = None
    ) -> None:
        """Set a gauge metric."""
        async with self._lock:
            key = self._make_key(name, labels)
            self._gauges[key] = value
            
            metric = Metric(
                name=name,
                type=MetricType.GAUGE,
                value=value,
                timestamp=datetime.now(timezone.utc),
                labels=labels or {},
            )
            self._store_metric(metric)
    
    async def histogram(
        self,
        name: str,
        value: float,
        labels: Optional[Dict[str, str]] = None
    ) -> None:
        """Record a histogram value."""
        async with self._lock:
            key = self._make_key(name, labels)
            if key not in self._histograms:
                self._histograms[key] = []
            self._histograms[key].append(value)
            
            # Keep only recent values
            if len(self._histograms[key]) > 1000:
                self._histograms[key] = self._histograms[key][-1000:]
            
            metric = Metric(
                name=name,
                type=MetricType.HISTOGRAM,
                value=value,
                timestamp=datetime.now(timezone.utc),
                labels=labels or {},
            )
            self._store_metric(metric)
    
    async def timing(
        self,
        name: str,
        duration_seconds: float,
        labels: Optional[Dict[str, str]] = None
    ) -> None:
        """Record a timing metric."""
        await self.histogram(f"{name}_seconds", duration_seconds, labels)
    
    def _make_key(self, name: str, labels: Optional[Dict[str, str]]) -> str:
        """Create a unique key for a metric."""
        if not labels:
            return name
        label_str = ",".join(f"{k}={v}" for k, v in sorted(labels.items()))
        return f"{name}{{{label_str}}}"
    
    def _store_metric(self, metric: Metric) -> None:
        """Store a metric in history."""
        if metric.name not in self._metrics:
            self._metrics[metric.name] = []
        
        self._metrics[metric.name].append(metric)
        
        # Trim history
        if len(self._metrics[metric.name]) > self.max_history:
            self._metrics[metric.name] = self._metrics[metric.name][-self.max_history:]
    
    async def get_metric(self, name: str) -> Optional[Metric]:
        """Get the latest value of a metric."""
        async with self._lock:
            if name in self._metrics and self._metrics[name]:
                return self._metrics[name][-1]
            return None
    
    async def get_metrics_history(
        self,
        name: str,
        limit: int = 100
    ) -> List[Metric]:
        """Get metric history."""
        async with self._lock:
            if name in self._metrics:
                return self._metrics[name][-limit:]
            return []

    async def get_all_current(self) -> Dict[str, float]:
        """Get the latest values for all metrics, including counters and gauges."""
        async with self._lock:
            result = {}
            # Latest from histograms/metrics
            for name, history in self._metrics.items():
                if history:
                    result[name] = history[-1].value
            # Current from counters and gauges
            result.update(self._counters)
            result.update(self._gauges)
            return result
    
    async def export_prometheus(self) -> str:
        """Export metrics in Prometheus format."""
        async with self._lock:
            lines = []
            
            # Export counters
            for key, value in self._counters.items():
                lines.append(f"# TYPE {key.split('{')[0]} counter")
                lines.append(f"{key} {value}")
            
            # Export gauges
            for key, value in self._gauges.items():
                lines.append(f"# TYPE {key.split('{')[0]} gauge")
                lines.append(f"{key} {value}")
            
            return "\n".join(lines)


class EventBus:
    """Event bus for publishing and subscribing to events."""
    
    def __init__(self, max_history: int = 1000):
        self.max_history = max_history
        self._events: List[Event] = []
        self._subscribers: Dict[EventType, List[Callable[[Event], Awaitable[None]]]] = {}
        self._all_subscribers: List[Callable[[Event], Awaitable[None]]] = []
        self._lock = asyncio.Lock()
    
    async def publish(self, event: Event) -> None:
        """Publish an event to all subscribers."""
        async with self._lock:
            self._events.append(event)
            
            # Trim history
            if len(self._events) > self.max_history:
                self._events = self._events[-self.max_history:]
        
        # Notify subscribers
        tasks = []
        
        # Type-specific subscribers
        if event.type in self._subscribers:
            for callback in self._subscribers[event.type]:
                tasks.append(callback(event))
        
        # All-event subscribers
        for callback in self._all_subscribers:
            tasks.append(callback(event))
        
        if tasks:
            # Phase 3 hardening: asyncio.wait with timeout replaces bare asyncio.gather
            # to prevent hung event subscribers from blocking the entire event pipeline
            futures = [asyncio.ensure_future(t) for t in tasks]
            done, pending = await asyncio.wait(futures, timeout=30.0)
            if pending:
                logger.warning(
                    f"EventBus.publish: {len(pending)}/{len(futures)} subscriber callbacks "
                    f"timed out after 30s for event {event.type.value}, cancelling"
                )
                for p in pending:
                    p.cancel()
                await asyncio.wait(pending, timeout=5.0)
    
    def subscribe(
        self,
        event_type: EventType,
        callback: Callable[[Event], Awaitable[None]]
    ) -> None:
        """Subscribe to a specific event type."""
        if event_type not in self._subscribers:
            self._subscribers[event_type] = []
        self._subscribers[event_type].append(callback)
    
    def subscribe_all(
        self,
        callback: Callable[[Event], Awaitable[None]]
    ) -> None:
        """Subscribe to all events."""
        self._all_subscribers.append(callback)
    
    def unsubscribe(
        self,
        event_type: EventType,
        callback: Callable[[Event], Awaitable[None]]
    ) -> None:
        """Unsubscribe from an event type."""
        if event_type in self._subscribers:
            self._subscribers[event_type] = [
                cb for cb in self._subscribers[event_type]
                if cb != callback
            ]
    
    async def get_events(
        self,
        event_type: Optional[EventType] = None,
        limit: int = 100,
        since: Optional[datetime] = None
    ) -> List[Event]:
        """Get events from python.history."""
        async with self._lock:
            events = self._events
            
            if event_type:
                events = [e for e in events if e.type == event_type]
            
            if since:
                events = [e for e in events if e.timestamp > since]
            
            return events[-limit:]


class AlertManager:
    """Manages alerts and notifications."""
    
    def __init__(self):
        self._alerts: Dict[str, Alert] = {}
        self._handlers: List[Callable[[Alert], Awaitable[None]]] = []
        self._lock = asyncio.Lock()
    
    async def fire(
        self,
        severity: AlertSeverity,
        title: str,
        message: str,
        source: str,
        labels: Optional[Dict[str, str]] = None
    ) -> Alert:
        """Fire a new alert."""
        alert = Alert(
            id=str(uuid.uuid4())[:8],
            severity=severity,
            title=title,
            message=message,
            timestamp=datetime.now(timezone.utc),
            source=source,
            labels=labels or {},
        )
        
        async with self._lock:
            self._alerts[alert.id] = alert
        
        # Notify handlers
        for handler in self._handlers:
            try:
                await handler(alert)
            except Exception as e:
                logger.error(f"Alert handler error: {e}")
        
        logger.warning(f"Alert fired: [{severity.value}] {title}: {message}")
        return alert
    
    async def resolve(self, alert_id: str) -> bool:
        """Resolve an alert."""
        async with self._lock:
            if alert_id in self._alerts:
                self._alerts[alert_id].resolved = True
                self._alerts[alert_id].resolved_at = datetime.now(timezone.utc)
                return True
            return False
    
    def add_handler(
        self,
        handler: Callable[[Alert], Awaitable[None]]
    ) -> None:
        """Add an alert handler."""
        self._handlers.append(handler)
    
    async def get_active_alerts(self) -> List[Alert]:
        """Get all active (unresolved) alerts."""
        async with self._lock:
            return [a for a in self._alerts.values() if not a.resolved]
    
    async def get_all_alerts(self, limit: int = 100) -> List[Alert]:
        """Get all alerts."""
        async with self._lock:
            alerts = list(self._alerts.values())
            return sorted(alerts, key=lambda a: a.timestamp, reverse=True)[:limit]


class Tracer:
    """Distributed tracing support."""
    
    def __init__(self, service_name: str = "agix"):
        self.service_name = service_name
        self._spans: Dict[str, Span] = {}
        self._traces: Dict[str, List[str]] = {}  # trace_id -> span_ids
        self._lock = asyncio.Lock()
    
    def start_trace(self) -> str:
        """Start a new trace and return trace_id."""
        return str(uuid.uuid4())
    
    async def start_span(
        self,
        operation_name: str,
        trace_id: Optional[str] = None,
        parent_span_id: Optional[str] = None,
        tags: Optional[Dict[str, str]] = None
    ) -> Span:
        """Start a new span."""
        trace_id = trace_id or self.start_trace()
        span_id = str(uuid.uuid4())[:16]
        
        span = Span(
            trace_id=trace_id,
            span_id=span_id,
            parent_span_id=parent_span_id,
            operation_name=operation_name,
            start_time=datetime.now(timezone.utc),
            tags=tags or {},
        )
        
        async with self._lock:
            self._spans[span_id] = span
            
            if trace_id not in self._traces:
                self._traces[trace_id] = []
            self._traces[trace_id].append(span_id)
        
        return span
    
    async def end_span(
        self,
        span_id: str,
        status: str = "ok"
    ) -> Optional[Span]:
        """End a span."""
        async with self._lock:
            if span_id in self._spans:
                span = self._spans[span_id]
                span.end_time = datetime.now(timezone.utc)
                span.status = status
                return span
            return None
    
    async def add_span_log(
        self,
        span_id: str,
        message: str,
        fields: Optional[Dict[str, Any]] = None
    ) -> None:
        """Add a log entry to a span."""
        async with self._lock:
            if span_id in self._spans:
                self._spans[span_id].logs.append({
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "message": message,
                    "fields": fields or {},
                })
    
    async def get_trace(self, trace_id: str) -> List[Span]:
        """Get all spans for a trace."""
        async with self._lock:
            if trace_id in self._traces:
                return [
                    self._spans[span_id]
                    for span_id in self._traces[trace_id]
                    if span_id in self._spans
                ]
            return []


class ObserverMesh:
    """
    Central observer mesh for distributed monitoring.
    
    Combines metrics, events, alerts, and tracing into a unified
    observability layer for the agent swarm.
    """
    
    _instance: Optional[ObserverMesh] = None

    @classmethod
    def get_instance(cls, **kwargs) -> ObserverMesh:
        """Get or create singleton instance of ObserverMesh."""
        if cls._instance is None:
            cls._instance = cls(**kwargs)
        return cls._instance

    def __init__(
        self,
        service_name: str = "agix",
        metrics_history: int = 10000,
        events_history: int = 1000,
    ):
        self.service_name = service_name
        self.metrics = MetricsCollector(max_history=metrics_history)
        self.events = EventBus(max_history=events_history)
        self.alerts = AlertManager()
        self.tracer = Tracer(service_name=service_name)
        
        self._running = False
        self._health_check_task: Optional[asyncio.Task] = None
        
        # Register default event handlers
        self._setup_default_handlers()
    
    def _setup_default_handlers(self) -> None:
        """Set up default event handlers for metrics."""
        async def on_task_started(event: Event):
            await self.metrics.increment(
                "tasks_started_total",
                labels={"source": event.source}
            )
        
        async def on_task_completed(event: Event):
            await self.metrics.increment(
                "tasks_completed_total",
                labels={"source": event.source}
            )
            if "duration" in event.data:
                await self.metrics.timing(
                    "task_duration",
                    event.data["duration"],
                    labels={"source": event.source}
                )
        
        async def on_task_failed(event: Event):
            await self.metrics.increment(
                "tasks_failed_total",
                labels={"source": event.source}
            )
        
        async def on_error(event: Event):
            await self.metrics.increment(
                "errors_total",
                labels={
                    "source": event.source,
                    "error_type": event.data.get("error_type", "unknown"),
                }
            )
        
        self.events.subscribe(EventType.TASK_STARTED, on_task_started)
        self.events.subscribe(EventType.TASK_COMPLETED, on_task_completed)
        self.events.subscribe(EventType.TASK_FAILED, on_task_failed)
        self.events.subscribe(EventType.ERROR_OCCURRED, on_error)
    
    async def start(self) -> None:
        """Start the observer mesh."""
        self._running = True
        self._start_health_check()
        logger.info("Observer mesh started")
    
    def _start_health_check(self) -> None:
        """Start or restart health check in the current event loop."""
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            return
        # Cancel stale task from a previous loop
        if self._health_check_task and not self._health_check_task.done():
            self._health_check_task.cancel()
        self._health_check_task = loop.create_task(self._health_check_loop())
    
    async def stop(self) -> None:
        """Stop the observer mesh."""
        self._running = False
        if self._health_check_task:
            self._health_check_task.cancel()
            try:
                await self._health_check_task
            except (asyncio.CancelledError, RuntimeError):
                logger.debug("[ObserverMesh] Health check task cancelled during stop")
        logger.info("Observer mesh stopped")
    
    async def _health_check_loop(self) -> None:
        """Periodic health check loop."""
        while self._running:
            try:
                # Update health metrics
                await self.metrics.gauge("observer_mesh_healthy", 1.0)
                await self.metrics.gauge(
                    "observer_mesh_uptime_seconds",
                    time.time()
                )
                
                await asyncio.sleep(30)  # Check every 30 seconds
            except asyncio.CancelledError:
                logger.debug("[ObserverMesh] Health check loop cancelled — shutting down gracefully")
                break
            except RuntimeError as e:
                # Handle "Future attached to a different loop" (#917)
                if "different loop" in str(e) or "attached to a different loop" in str(e):
                    logger.debug(f"Health check loop mismatch, rebinding: {e}")
                    self._start_health_check()
                    break
                logger.error(f"Health check error: {e}")
            except Exception as e:
                logger.error(f"Health check error: {e}")
    
    # ==========================================================================
    # Convenience Methods
    # ==========================================================================
    
    async def record_task_start(
        self,
        task_id: str,
        task_type: str,
        source: str,
        trace_id: Optional[str] = None
    ) -> Span:
        """Record a task start event and create a span."""
        span = await self.tracer.start_span(
            operation_name=f"task:{task_type}",
            trace_id=trace_id,
            tags={"task_id": task_id, "task_type": task_type},
        )
        
        await self.events.publish(Event(
            id=str(uuid.uuid4())[:8],
            type=EventType.TASK_STARTED,
            timestamp=datetime.now(timezone.utc),
            source=source,
            data={"task_id": task_id, "task_type": task_type},
            trace_id=span.trace_id,
            span_id=span.span_id,
        ))
        
        return span
    
    async def record_task_complete(
        self,
        task_id: str,
        source: str,
        span: Span,
        duration: float,
        success: bool = True
    ) -> None:
        """Record a task completion event."""
        await self.tracer.end_span(
            span.span_id,
            status="ok" if success else "error"
        )
        
        event_type = EventType.TASK_COMPLETED if success else EventType.TASK_FAILED
        
        await self.events.publish(Event(
            id=str(uuid.uuid4())[:8],
            type=event_type,
            timestamp=datetime.now(timezone.utc),
            source=source,
            data={
                "task_id": task_id,
                "duration": duration,
                "success": success,
            },
            trace_id=span.trace_id,
            span_id=span.span_id,
        ))
    
    async def record_error(
        self,
        error: Exception,
        source: str,
        context: Optional[Dict[str, Any]] = None,
        span: Optional[Span] = None
    ) -> None:
        """Record an error event."""
        await self.events.publish(Event(
            id=str(uuid.uuid4())[:8],
            type=EventType.ERROR_OCCURRED,
            timestamp=datetime.now(timezone.utc),
            source=source,
            data={
                "error_type": type(error).__name__,
                "error_message": str(error),
                "context": context or {},
            },
            trace_id=span.trace_id if span else None,
            span_id=span.span_id if span else None,
        ))
        
        if span:
            await self.tracer.add_span_log(
                span.span_id,
                f"Exception: {error}",
                {"error_type": type(error).__name__}
            )
    
    async def check_and_alert(
        self,
        metric_name: str,
        threshold: float,
        comparison: str = "gt",
        severity: AlertSeverity = AlertSeverity.WARNING,
        title: str = "",
        source: str = "observer_mesh"
    ) -> Optional[Alert]:
        """Check a metric against a threshold and fire alert if needed."""
        metric = await self.metrics.get_metric(metric_name)
        if not metric:
            return None
        
        should_alert = False
        if comparison == "gt" and metric.value > threshold:
            should_alert = True
        elif comparison == "lt" and metric.value < threshold:
            should_alert = True
        elif comparison == "eq" and metric.value == threshold:
            should_alert = True
        elif comparison == "gte" and metric.value >= threshold:
            should_alert = True
        elif comparison == "lte" and metric.value <= threshold:
            should_alert = True
        
        if should_alert:
            return await self.alerts.fire(
                severity=severity,
                title=title or f"Metric {metric_name} threshold exceeded",
                message=f"{metric_name} = {metric.value} (threshold: {comparison} {threshold})",
                source=source,
                labels={"metric": metric_name},
            )
        
        return None
    
    # ==========================================================================
    # Export Methods
    # ==========================================================================
    
    async def record_api_request(
        self,
        service: str,
        method: str,
        duration: float,
        success: bool = True,
        trace_id: Optional[str] = None
    ) -> None:
        """Record an API request event."""
        await self.metrics.timing(
            "api_request_duration",
            duration,
            labels={"service": service, "method": method, "success": str(success)}
        )
        
        await self.events.publish(Event(
            id=str(uuid.uuid4())[:8],
            type=EventType.API_REQUEST_COMPLETED if success else EventType.ERROR_OCCURRED,
            timestamp=datetime.now(timezone.utc),
            source="api_client",
            data={
                "service": service,
                "method": method,
                "duration": duration,
                "success": success,
            },
            trace_id=trace_id,
        ))

    async def record_tool_execution(
        self,
        tool_name: str,
        duration: float,
        success: bool = True,
        trace_id: Optional[str] = None
    ) -> None:
        """Record a tool execution event."""
        await self.metrics.timing(
            "tool_execution_duration",
            duration,
            labels={"tool": tool_name, "success": str(success)}
        )
        
        await self.events.publish(Event(
            id=str(uuid.uuid4())[:8],
            type=EventType.TOOL_EXECUTION_COMPLETED if success else EventType.ERROR_OCCURRED,
            timestamp=datetime.now(timezone.utc),
            source="tool_executor",
            data={
                "tool": tool_name,
                "duration": duration,
                "success": success,
            },
            trace_id=trace_id,
        ))

    async def record_prompt_rendering(
        self,
        duration: float,
        trace_id: Optional[str] = None
    ) -> None:
        """Record a prompt rendering event."""
        await self.metrics.timing(
            "prompt_rendering_duration",
            duration
        )
        
        await self.events.publish(Event(
            id=str(uuid.uuid4())[:8],
            type=EventType.PROMPT_RENDERED,
            timestamp=datetime.now(timezone.utc),
            source="prompt_engine",
            data={
                "duration": duration,
            },
            trace_id=trace_id,
        ))

    async def get_dashboard_data(self) -> Dict[str, Any]:
        """Get data for a monitoring dashboard."""
        current_metrics = await self.metrics.get_all_current()
        active_alerts = await self.alerts.get_active_alerts()
        recent_events = await self.events.get_events(limit=50)
        
        return {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "service": self.service_name,
            "metrics": current_metrics,
            "active_alerts": [a.to_dict() for a in active_alerts],
            "recent_events": [e.to_dict() for e in recent_events],
            "health": {
                "status": "healthy" if not active_alerts else "degraded",
                "alert_count": len(active_alerts),
            },
        }
    
    async def export_prometheus_metrics(self) -> str:
        """Export metrics in Prometheus format."""
        return await self.metrics.export_prometheus()


# =============================================================================
# Factory Function
# =============================================================================

def create_observer_mesh(
    service_name: str = "agix",
    metrics_history: int = 10000,
    events_history: int = 1000,
) -> ObserverMesh:
    """Create an observer mesh instance."""
    return ObserverMesh(
        service_name=service_name,
        metrics_history=metrics_history,
        events_history=events_history,
    )


# =============================================================================
# Context Manager for Tracing
# =============================================================================

class TracingContext:
    """Context manager for automatic span management."""
    
    def __init__(
        self,
        observer: ObserverMesh,
        operation_name: str,
        trace_id: Optional[str] = None,
        parent_span_id: Optional[str] = None,
        tags: Optional[Dict[str, str]] = None
    ):
        self.observer = observer
        self.operation_name = operation_name
        self.trace_id = trace_id
        self.parent_span_id = parent_span_id
        self.tags = tags
        self.span: Optional[Span] = None
    
    async def __aenter__(self) -> Span:
        self.span = await self.observer.tracer.start_span(
            operation_name=self.operation_name,
            trace_id=self.trace_id,
            parent_span_id=self.parent_span_id,
            tags=self.tags,
        )
        return self.span
    
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        if self.span:
            status = "error" if exc_type else "ok"
            await self.observer.tracer.end_span(self.span.span_id, status)
            
            if exc_type:
                await self.observer.tracer.add_span_log(
                    self.span.span_id,
                    f"Exception: {exc_val}",
                    {"exception_type": exc_type.__name__ if exc_type else None}
                )
